import { readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';

import { blogSource, docsSource } from '@/lib/source';

/**
 * The static search index, served as a file.
 *
 * **A static export has no server, so the index is a file and this route is how the
 * file is written.** `revalidate = false` is the marker Next accepts on a route
 * handler under `output: 'export'`; without it the export build fails rather than
 * emitting nothing. The bar's dialog fetches this once, on the first search, which is
 * why a static export can have search at all: there is no request to make beyond that
 * one, and no runtime between them.
 *
 * **The shape is Prism's, not this site's.** `SearchDialog` declares the four fields a
 * result is drawn from, and a consumer's index is a contract between a build step the
 * consumer owns and a dialog it does not.
 *
 * Thirty-five entries are indexed here: the thirty-one `.mdx` files the loaders
 * publish, and the four pages this site writes as React. So unlike the company site
 * this one reads the corpus rather than writing it out. Both halves are still joined
 * rather than trusted: the list of pages comes from the loaders, which is where a
 * draft is excluded for the same reason it is excluded from the routes, and the prose
 * comes from the MDX beside each page, because the compiled body is a component and
 * not text. A page with no file beside it fails this build rather than being indexed
 * with a title and no body: a page a reader can reach and a search cannot read is the
 * silent half-published defect that join exists to prevent.
 */

/** One page in the index. The four fields a result is drawn from, and no more. */
interface IndexEntry {
  id: string;
  title: string;
  url: string;
  description?: string;
  content?: string;
  breadcrumbs?: string[];
}

/**
 * The pages this site writes as React rather than as MDX.
 *
 * The landing and About are hand-written pages, and the documentation and blog
 * indexes are generated by the routes rather than by a document, so none of the four
 * is in a content tree. The leading line of each is the one the page itself opens
 * with, so a search result for the landing reads as the landing rather than as a
 * title the reader has already seen in the bar.
 */
const OWN_PAGES: readonly IndexEntry[] = [
  {
    id: '/',
    title: 'Nexus, software that builds software',
    url: '/',
    description: 'Nexus is the Agent Factory. A coding agent takes a GitHub issue and returns a reviewed, merged pull request.',
    content:
      'Nexus is the Agent Factory, an autonomous software-creation engine that turns a GitHub issue into a reviewed, merged pull request. In active development, and the design is public.',
  },
  {
    id: '/about',
    title: 'About Nexus',
    url: '/about',
    description: 'What Nexus is, who builds it, and what it is honest about not doing yet.',
  },
  {
    id: '/docs',
    title: 'Documentation',
    url: '/docs',
    description: 'The six sections of the Nexus documentation, and what each one covers.',
  },
  {
    id: '/blog',
    title: 'The Nexus blog',
    url: '/blog',
    description: 'Notes on agent-driven development and the factory around it.',
  },
];

/** The two content trees, and where each one's documents live. */
const TREES = [
  { dir: 'docs', baseUrl: '/docs', source: docsSource, folders: true },
  { dir: 'blog', baseUrl: '/blog', source: blogSource, folders: false },
] as const;

/** A post's frontmatter title and description, and nothing else. */
function frontmatter(source: string): { title?: string; description?: string } {
  const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(source);
  if (!match) return {};
  const fields: { title?: string; description?: string } = {};
  for (const line of (match[1] ?? '').split(/\r?\n/)) {
    const field = /^(title|description):\s*(.+)$/.exec(line);
    if (field) {
      fields[field[1] as 'title' | 'description'] = (field[2] ?? '').trim().replace(/^['"]|['"]$/g, '');
    }
  }
  return fields;
}

/**
 * A document's prose, with the markup taken off.
 *
 * Good enough to match a word a reader can see on the page against, which is the whole
 * of what a substring search does with it. Frontmatter, headings, emphasis, code ticks,
 * link syntax and list bullets are removed; the words and the spaces between them are
 * left, because those are what the query is matched against.
 */
function prose(source: string): string {
  return source
    .replace(/^---\r?\n[\s\S]*?\r?\n---/, ' ')
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/`([^`]*)`/g, '$1')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/^\s{0,3}#{1,6}\s+/gm, '')
    .replace(/^\s*[-*+]\s+/gm, '')
    .replace(/^\s*\d+\.\s+/gm, '')
    .replace(/<[^>]+>/g, ' ')
    .replace(/[*_>]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/** Every `.mdx` under a directory, as paths relative to it. */
function documents(root: string, prefix = ''): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) found.push(...documents(path.join(root, entry.name), relative));
    else if (entry.name.endsWith('.mdx')) found.push(relative);
  }
  return found;
}

/**
 * The section a document sits in, as the reader will see it.
 *
 * The folder is the join key and its `meta.json` is the source of the name, because a
 * breadcrumb is reader-facing text and the folder happens to be named in lower case.
 * A document whose path has no folder in it is the Introduction, which sits above the
 * sections rather than inside one, and it carries no trail; a section with no readable
 * `meta.json` falls back to its name with the first letter raised, because a missing
 * trail is worse than a plain one and the docs-tree gate already refuses a tree that
 * has no `meta.json` at all.
 */
function sectionOf(tree: string, relative: string): string[] | undefined {
  if (tree !== 'docs') return undefined;
  const segments = relative.split('/');
  // No folder means no section: `introduction.mdx` is the one document in this corpus
  // that sits at the top of the tree, and its file is named for what it is.
  const [folder, ...rest] = segments;
  if (folder === undefined || rest.length === 0) return undefined;
  try {
    const meta = JSON.parse(
      readFileSync(path.join(process.cwd(), 'content', tree, folder, 'meta.json'), 'utf8'),
    ) as { title?: string };
    if (typeof meta.title === 'string' && meta.title.length > 0) return [meta.title];
  } catch {
    // Fall through to the folder name: a section whose file cannot be read is a
    // finding for another gate, and a search result is the wrong place to fail over.
  }
  return [folder.charAt(0).toUpperCase() + folder.slice(1)];
}

/** One tree's published pages, read from its loader and joined to the MDX beside it. */
function entriesFor(tree: (typeof TREES)[number]): IndexEntry[] {
  const root = path.join(process.cwd(), 'content', tree.dir);
  const onDisk = new Set(documents(root));

  return tree.source
    .getPages()
    .filter((page) => {
      // A draft is excluded here for the same reason it is excluded from the routes,
      // from the blog index and from prev/next: a page that cannot be reached cannot be
      // a search result that goes nowhere.
      const data = page.data as { draft?: boolean };
      return !data.draft;
    })
    .map((page) => {
      // The route is the join key on both sides, so the loader decides the URL and the
      // tree is only read to find the words.
      const relative = page.url.replace(new RegExp(`^${tree.baseUrl}/?`), '');
      const candidates = tree.folders
        ? [`${relative}.mdx`, `${relative}/index.mdx`]
        : [`${relative}/index.mdx`, `${relative}.mdx`];

      const match = candidates.find((candidate) => onDisk.has(candidate));
      if (!match) {
        throw new Error(
          `search index: ${page.url} is published but none of ${candidates.join(' or ')} exists ` +
            `under content/${tree.dir}, so a route a reader can reach has no body for a search to ` +
            'match. The routes and the files are read from one tree on purpose; this is that join failing.',
        );
      }

      const source = readFileSync(path.join(root, ...match.split('/')), 'utf8');
      const fields = frontmatter(source);
      return {
        id: page.url,
        // The loader's own title, not the file's: the loader applies the schema and the
        // defaults, so a page whose frontmatter omits a field gets the value a reader
        // sees rather than the one a regex found.
        title: (page.data as { title?: string }).title ?? fields.title ?? page.url,
        url: page.url,
        description: (page.data as { description?: string }).description ?? fields.description,
        content: prose(source),
        // The section is the trail a reader needs when two pages share a name, and
        // this corpus is six sections of similarly-titled documents. The Introduction
        // carries none, because it sits above the sections rather than inside one.
        breadcrumbs: sectionOf(tree.dir, match),
      };
    });
}

function index(): IndexEntry[] {
  return [...OWN_PAGES, ...TREES.flatMap(entriesFor)];
}

export const revalidate = false;

export function staticGET(): Response {
  return Response.json(index());
}

export const GET = staticGET;
